apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: demo-frontend
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: coitlearning/demo-frontend:v15
          env:
            - name: COIT_BACKEND_URL
              value: "http://demo-backend1.102.12.12.45.sslip.io"
          ports:
            - containerPort: 80
              protocol: TCP 
