apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: demo-frontend
spec:
    spec:
      containers:
        - image: coitlearning/demo-frontend:v3
          imagePullPolicy: Always                         # 7
          name: demo-frontend
          ports:
            - containerPort: 8080
