apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - demo-frontend-deployment.yaml
  - service-demo-frontend-lb.yaml
  - demo-frontend-ingress.yaml

patches:
- path: demo-frontend-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: demo-frontend

namePrefix: customer1-
nameSuffix: -myapp
commonLabels:
  customer: customer1 
  location: mumbai
  managed-by: kustomize

images:
  - newName: coitlearning/demo-frontend
    newTag: v3
    name: coitlearning/demo-frontend

configMapGenerator:
- name: demo-frontend-config
  literals:
  - JAVA_HOME=/opt/java/jdk
  - JAVA_TOOL_OPTIONS=-agentlib:hprof
  - JAVA_URL="demo-backend1:5000"
- name: demo-frontend-props
  files:
  - config.properties
  - provider.properties
- name: values-from-props
  envs:
  - config.properties
  - provider.properties

