apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - demo-frontend-deployment.yaml
  - service-demo-frontend-lb.yaml

configMapGenerator:
- name: my-frontend-env-vars
  literals:
  - JAVA_HOME=/opt/java/jdk
  - JAVA_TOOL_OPTIONS=-agentlib:hprof
  - DB_NAME=mydb
- name: my-frontend-props
  files:
  - myapp.properties
- name: my-frontend-props-from-file
  envs:
  - myapp.properties

replicas:
- name: demo-frontend 
  count: 3

namespace: default

commonLabels:
  customer: southvalley
  owner: basil
  app: frontend

commonAnnotations:
  customer: southvalley
  owner: basil
  app: frontend

namePrefix: customer1-
nameSuffix: -dev

patches:
  - patch: |-
      - op: add
        path: /metadata/labels/app.kubernetes.io~1version 
        value: 1.21.0
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: basilvarghese/demo-frontend:1.0.0
    target:
      group: apps
      version: v1
      kind: Deployment