apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: simple-microservice
build:
  tagPolicy:
    customTemplate:
      template: "{{.DATE}}_{{.GIT}}"
      components:
      - name: DATE
        dateTime:
          format: "2006-01-02"
          timezone: "UTC"
      - name: GIT
        gitCommit:
          variant: AbbrevCommitSha
  artifacts:
  - image: asia.gcr.io/devops-learning-347802/demo-backend1
    context: demo-backend1
    docker:
      dockerfile: Dockerfile-multistage
  - image: asia.gcr.io/devops-learning-347802/demo-backend2
    context: demo-backend2
    docker:
      dockerfile: Dockerfile
  - image: asia.gcr.io/devops-learning-347802/demo-frontend
    context: demo-frontend
    docker:
      dockerfile: Dockerfile-multistage
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - resource-manifests/demo-backend1-deployment.yaml
    - resource-manifests/demo-backend2-deployment.yaml
    - resource-manifests/demo-frontend-deployment.yaml
    - resource-manifests/service-demo-backend1-lb.yaml
    - resource-manifests/service-demo-backend2.yaml
    - resource-manifests/service-demo-frontend-lb.yaml
profiles:
  - name: dev
    activation:
      - env: CURRENTENV=dev
    build:
      artifacts:
      - image: demo-backend1
        context: demo-backend1
        docker:
          dockerfile: Dockerfile
      - image: demo-backend2
        context: demo-backend2
        docker:
          dockerfile: Dockerfile
      - image: demo-frontend
        context: demo-frontend
        docker:
          dockerfile: Dockerfile
      local:
        push: true
    deploy:
      kubeContext: arn:aws:eks:ap-south-1:210607809234:cluster/aws-mumbai-all
      kubectl:
        manifests:
        - resource-manifests/demo-backend1-deployment.yaml
        - resource-manifests/demo-backend2-deployment.yaml
        - resource-manifests/demo-frontend-deployment.yaml
        - resource-manifests/service-demo-backend1-lb.yaml
        - resource-manifests/service-demo-backend2.yaml
        - resource-manifests/service-demo-frontend-lb.yaml
  - name: production
    activation:
      - env: CURRENTENV=prod
    build:
      artifacts:
      - image: demo-backend1
        context: demo-backend1
        docker:
          dockerfile: Dockerfile
      - image: demo-backend2
        context: demo-backend2
        docker:
          dockerfile: Dockerfile
      - image: demo-frontend
        context: demo-frontend
        docker:
          dockerfile: Dockerfile
      local:
        push: true
    deploy:
      kubeContext: arn:aws:eks:ap-south-1:210607809234:cluster/aws-mumbai-all
      kubectl:
        manifests:
        - resource-manifests/demo-backend1-deployment.yaml
        - resource-manifests/demo-backend2-deployment.yaml
        - resource-manifests/demo-frontend-deployment.yaml
        - resource-manifests/service-demo-backend1-lb.yaml
        - resource-manifests/service-demo-backend2.yaml
        - resource-manifests/service-demo-frontend-lb.yaml

portForward:
- resourceType: service
  resourceName: demo-frontend-lb
  port: 80
  localPort: 4500 # *Optional*
- resourceType: service
  resourceName: demo-backend1-lb
  port: 80
  localPort: 4600 # *Optional*
