apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../demo-backend1
  - ../../demo-frontend

replicas:
- name: demo-backend1
  count: 5
- name: demo-frontend 
  count: 10

namespace: production