apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../demo-frontend

replicas:
- name: demo-frontend 
  count: 4

images:
- name: coitlearning/demo-frontend
  newName: coitlearning/demo-frontend
  newTag: '9'

namespace: staging
