apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - demo-backend1-cm-files.yaml
  - demo-backend1-cm.yaml
  - demo-backend1-deployment.yaml
  - demo-backend1-ingress.yaml
  - demo-backend1-pvc-staticfiles.yaml
  - demo-backend1-secrets.yaml
  - demo-backend1-pvc.yaml
  - service-demo-backend1-lb.yaml

replicas:
- name: demo-backend1
  count: 1