apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: demo-frontend
  labels:
    app: demo-frontend
spec:
  selector:
    matchLabels:
      app: demo-frontend
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: demo-frontend                                  # 6
    spec:
      volumes:
        - name: nginx-root
          persistentVolumeClaim:
            claimName: demo-frontend
        - name: datastore
          persistentVolumeClaim:
            claimName: demo-frontend-fast
      containers:
        - image: asia.gcr.io/devops-learning-347802/demo-frontend:1.0.0
          imagePullPolicy: IfNotPresent                         # 7
          name: demo-frontend
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-root
            - mountPath: /var/lib/sql
              name: datastore
