apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend1
  labels:
    app: demo-backend1
spec:
  selector:
    matchLabels:
      app: demo-backend1
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: demo-backend1
    spec:
      containers:
      - image: coitlearning/demo-backend1:v1
        imagePullPolicy: IfNotPresent
        name: demo-backend1
        ports:
          - containerPort: 8080
        env:
          - name: SA_LOGIC_API_URL
            valueFrom:
              configMapKeyRef:
                name: demo-backend1-config 
                key: python-url
