apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - demo-frontend-deployment.yaml
  - service-demo-frontend-lb.yaml

replicas:
- name: demo-frontend 
  count: 3

namespace: default
